micronaut:
    application:
        name: gateway
    server:
        port: 8080
    cors:
        enabled: true
        configurations:
            web:
                allowedMethods: ["POST", "GET"]
---
consul:
  client:
    registration:
      enabled: false
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.