micronaut:
    application:
        name: pricing-service
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
#tracing:
#  zipkin:
#    enabled: true
#    http:
#      url: http://localhost:9411
#      sampler:
#        probability: 0.1
