micronaut:
    application:
        name: pricing-service
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
#tracing:
#  zipkin:
#    enabled: true
#    http:
#      url: http://localhost:9411
#      sampler:
#        probability: 0.1



datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver

jpa:
 default:
    packages-to-scan:
        - 'pl.altkom.asc.lab.micronaut.poc.pricing.domain'
    properties:
        hibernate:
            hbm2ddl:
                auto: update
            show_sql: true