kind: Service
apiVersion: v1
metadata:
  name: pricing-service
  labels:
    srv: pricing-service
spec:
  type: ClusterIP
  selector:
    srv: pricing-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
