kind: Deployment
apiVersion: apps/v1
metadata:
  name: auth-service
  labels:
    srv: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      srv: auth-service
  template:
    metadata:
      labels:
        srv: auth-service
    spec:
      containers:
      - name: auth-service
        image: ascmn/auth-service:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_PORT
          value: "80"
        - name: ZIPKIN_HOST
          value: zipkin
        - name: ZIPKIN_PORT
          value: "9411"