micronaut:
  application:
      name: product-service
  metrics:
    enabled: true
---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/products-demo"
    cluster:
      maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
endpoints:
  health:
    enabled: true
  metrics:
    enabled: true
