kind: Service
apiVersion: v1
metadata:
  name: jsreport
  labels:
    srv: jsreport
spec:
  type: LoadBalancer
  selector:
    srv: jsreport
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5488