definitions:
  config:
    /hippo:namespaces/minicms/product:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: f685b182-5025-4162-86a2-d3bea0e17769
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: d3ac3ff5-0453-413a-9892-fe918147303f
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: dea26e6b-ca22-4e91-a10b-865cec58737b
          hipposysedit:node: true
          hipposysedit:supertype: ['minicms:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/minicms/nt/1.0
          /name:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: minicms:name
            hipposysedit:primary: false
            hipposysedit:type: Html
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: minicms:description
            hipposysedit:primary: false
            hipposysedit:type: Html
        /hipposysedit:nodetype[2]:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 17156f65-083d-4ffe-a1bf-8a5a2b74c077
          hipposysedit:node: true
          hipposysedit:supertype: ['minicms:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          /name:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: minicms:name
            hipposysedit:primary: false
            hipposysedit:type: Html
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: minicms:description
            hipposysedit:primary: false
            hipposysedit:type: Html
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: minicms:product
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          jcr:mixinTypes: ['mix:referenceable']
          minicms:name: ''
          minicms:description: ''
          jcr:uuid: 1c2982ac-58c3-4267-9133-e07429110ad4
          hippostdpubwf:lastModificationDate: 2018-11-06T10:28:15.345+01:00
          hippostdpubwf:creationDate: 2018-11-06T10:28:15.346+01:00
        /hipposysedit:prototype[2]:
          jcr:primaryType: nt:unstructured
          jcr:mixinTypes: ['hippostd:publishableSummary', 'hippostd:relaxed', 'hippostdpubwf:document',
            'hippotranslation:translated', 'mix:referenceable']
          jcr:uuid: 3a8df921-da48-4605-8945-08b088a1f1b0
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2018-11-06T10:28:15.346+01:00
          hippostdpubwf:lastModificationDate: 2018-11-06T10:28:15.345+01:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          minicms:description: ''
          minicms:name: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /name:
            jcr:primaryType: frontend:plugin
            caption: Html
            field: name
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            caption: Html
            field: description
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
