kind: Service
apiVersion: v1
metadata:
  name: agent-portal-gateway
  labels:
    srv: agent-portal-gateway
spec:
  type: ClusterIP
  selector:
    srv: agent-portal-gateway
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
