---
micronaut:
    application:
        name: consul-zipkin-example
                
#Uncomment to set server port
#    server:
#        port: 8080

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

---
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
      sampler:
        probability: 0.1